# Generated by Django 3.2.8 on 2021-10-23 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='nome',
            new_name='departamento',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='id_departamento',
            field=models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='core.departamento'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='id_colaborador',
            field=models.ForeignKey(db_column='id_colaborador', on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='core.colaborador'),
        ),
    ]
